# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: &app vault-secrets-operator
#   namespace: argocd
#   metadata:
# spec:
#   project: default
#   sources:
#     - chart: *app
#       repoURL: https://helm.releases.hashicorp.com
#       targetRevision: 1.0.1
#       helm:
#         valuesObject:
#           defaultVaultConnection:
#             enabled: true
#             address: "http://vault.vault.svc.cluster.local:8200"
#             skipTLSVerify: false

#   destination:
#     server: https://kubernetes.default.svc
#     namespace: *app

#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
