apiVersion: gateway.networking.k8s.io/v1 
kind: HTTPRoute
metadata:
  name: homepage-httproute
  namespace: homepage
spec:
  parentRefs:
    name: envoy-shared-gateway
    namespace: envoy-gateway-system
  hostnames:
    - homepage.70ld.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: homepage
          port: 3000
