---
apiVersion: v1
kind: Secret
metadata:
  name: nessie-s3-credentials
  namespace: nessie
data:
  accessKeyId: R0s3NWVhMmVmZTc1MzIyOWM1Nzk2NjMxMWE=
  secretAccessKey: NGFhZDI0ZjE5NmE3OTQwNDBmZGI4ZDRjNjE2OWM4MzliODdlOWU4MzhhZTk1YzY1NDFlNzU1YzQ3MzVjYjg0Mw==
