# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-pihole 
  namespace: external-dns
type: Opaque
stringData:
  EXTERNAL_DNS_PIHOLE_PASSWORD: 123qwe!! 

