---
# Configuration file for k3s - /etc/rancher/k3s/config.yaml

# Node Configuration
node-name: "my-k3s-node"
token: 95e2850a0e0b505b8b677661885509a2

# TLS Configuration
tls-san: 192.168.5.200

data-dir: /var/lib/rancher/k3s

# ETCD configuration
etcd-snapshot-schedule-cron: "0 */6 * * *" #Schedule ETCD snapshots every 6 hours
etcd-snapshot-retention: 7 # Retain the last 7 snapshots
etcd-snapshot-dir: "/var/lib/rancher/k3s/etcd/snapshots" # Directory to store ETCD snapshots

disable:
  - "traefik"
  - "servicelb"
