apiVersion: v1
kind: ConfigMap
metadata:
  name: nebula-sync-config
  namespace: pihole
data:
  PRIMARY: "http://pihole-0.pihole.pihole.svc.cluster.local|'123qwe!!'"
  REPLICAS: "http://pihole-1.pihole.pihole.svc.cluster.local|'123qwe!!',http://pihole-2.pihole.pihole.svc.cluster.local|'123qwe!!'"
  FULL_SYNC: "false"
  RUN_GRAVITY: "false"
  CRON: "*/15 * * * *"

  CLIENT_SKIP_TLS_VERIFICATION: "true"

  TZ: "Europe/London"

  SYNC_CONFIG_DNS: "true"
  SYNC_CONFIG_DHCP: "false"
  SYNC_CONFIG_NTP: "false"
  SYNC_CONFIG_RESOLVER: "false"
  SYNC_CONFIG_DATABASE: "false"
  SYNC_CONFIG_MISC: "false"
  SYNC_CONFIG_DEBUG: "false"

  SYNC_GRAVITY_DHCP_LEASES: "false"
  SYNC_GRAVITY_GROUP: "false"
  SYNC_GRAVITY_AD_LIST: "true"
  SYNC_GRAVITY_AD_LIST_BY_GROUP: "true"
  SYNC_GRAVITY_DOMAIN_LIST: "true"
  SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP: "true"
  SYNC_GRAVITY_CLIENT: "false"
  SYNC_GRAVITY_CLIENT_BY_GROUP: "false"