apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-ingress
  labels:
    app.kubernetes.io/name: pihole-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare-dns-issuer"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - pihole-k8s.70ld.dev
      secretName: pihole-k8s-tls
  rules:
  - host: pihole-k8s.70ld.dev
    http:
      paths:
      - pathType: Prefix
        path: "/admin"
        backend:
          service:
            name: pihole-web-svc
            port: 
              number: 80
