apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: duckdb-ui-route
  namespace: duckdb
spec:
  parentRefs:
    - name: envoy-shared-gateway
      namespace: envoy-gateway-system
  hostnames:
    - 'duckdb.70ld.dev'
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: duckdb-ui
          port: 8080
