apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  namespace: cnpg-cluster
spec:
  description: "70LD PostgreSQL PROD Cluster"
  instances: 3
  startDelay: 3600
  stopDelay: 300
  primaryUpdateStrategy: unsupervised

  probes:
    startup:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5

  projectedVolumeTemplate:
    sources: []

  postgresql:
    parameters:
      shared_buffers: "256MB"

  resources:
    requests:
      memory: "750Mi"
      cpu: 250m
    limits:
      memory: "1Gi"
      cpu: 500m

  storage:
    storageClass: longhorn
    size: 8Gi

  bootstrap:
    initdb:
      database: main
      owner: paul
      secret:
        name: cnpg-cluster-user

  enableSuperuserAccess: true
  superuserSecret:
    name: cnpg-cluster-superuser

  managed:
    roles:
      # Role: My personal user
      - name: paul
        ensure: present
        comment: "Paul's CNPG Cluster User"
        login: true
        superuser: true
        passwordSecret:
          name: cnpg-cluster-user

      - name: authentik
        ensure: present
        comment: "Simple application user for Authentik"
        login: true
        superuser: true
        passwordSecret:
          name: cnpg-authentik-user

    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: postgres-rw-svc
              annotations:
                metallb.universe.tf/loadBalancerIPs: 192.168.7.80
            spec:
              type: LoadBalancer

  affinity:
    enablePodAntiAffinity: true
    topologyKey: failure-domain.beta.kubernetes.io/zone

  monitoring:
    enablePodMonitor: true
