kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: headlamp-ingress
  namespace: kube-system
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare-dns-issuer"
spec:
  ingressClassName: nginx
  tls:
  - secretName: headlamp-tls
    hosts:
    - headlamp.70ld.dev
  rules:
  - host: headlamp.70ld.dev 
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: headlamp-svc
            port:
              number: 80
