---
name: Format YAML
on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  yamlfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

        # Install Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

        # find errors with yamlfmt
      - name: Install yamlfmt
        run: go install github.com/google/yamlfmt/cmd/yamlfmt@latest
      - name: Run yamlfmt
        run: yamlfmt .

        # commit changes
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: format YAML files"
          file_pattern: "*.yaml *.yml"
